from __future__ import annotations
from typing import Protocol, Any


class GitHubReadOnlyEvidenceAdapter(Protocol):
    """Evidence-only interface. Mutation methods are intentionally absent."""
    def get_repository_metadata(self, repository: str) -> dict[str, Any]: ...
    def get_branch_head(self, repository: str, branch: str) -> dict[str, Any]: ...
    def get_commit_metadata(self, repository: str, sha: str) -> dict[str, Any]: ...
    def get_file_content_or_metadata(self, repository: str, ref: str, path: str) -> dict[str, Any]: ...
    def get_issue(self, repository: str, number: int) -> dict[str, Any]: ...
    def get_pull_request(self, repository: str, number: int) -> dict[str, Any]: ...
    def get_pull_request_files(self, repository: str, number: int) -> list[dict[str, Any]]: ...
    def get_check_runs_or_status(self, repository: str, sha: str) -> dict[str, Any]: ...
    def get_review_metadata(self, repository: str, number: int) -> list[dict[str, Any]]: ...
